#!/usr/bin/env python3
# Convert a PNG logo to a C pixel array (0xAARRGGBB) for the kernel GUI.
# No PNG decoder needed in the kernel; libdraw alpha-blits the result.
import sys
from PIL import Image

src = sys.argv[1] if len(sys.argv) > 1 else "assets/vibeoslogo-transparent.png"
out = sys.argv[2] if len(sys.argv) > 2 else "gui/core/src/gui_logo.c"
W   = int(sys.argv[3]) if len(sys.argv) > 3 else 320

im = Image.open(src).convert("RGBA")
H = round(im.height * W / im.width)
im = im.resize((W, H), Image.LANCZOS)
px = im.load()

vals = []
for y in range(H):
    for x in range(W):
        r, g, b, a = px[x, y]
        vals.append((a << 24) | (r << 16) | (g << 8) | b)

with open(out, "w") as f:
    f.write("/* Generated by gui/core/tools/genlogo.py from %s — do not edit. */\n" % src)
    f.write("#include <stdint.h>\n")
    f.write("extern \"C\" const int vibeos_logo_w = %d;\n" % W)
    f.write("extern \"C\" const int vibeos_logo_h = %d;\n" % H)
    f.write("extern \"C\" const uint32_t vibeos_logo[%d] = {\n" % (W * H))
    for i in range(0, len(vals), 12):
        f.write("  " + ",".join("0x%08x" % v for v in vals[i:i+12]) + ",\n")
    f.write("};\n")
print("wrote %s  (%dx%d, %d px)" % (out, W, H, W*H))
