/* gfx_font — runtime font model for libgfx.
 *
 * A font is baked at build time from a TrueType file into an antialiased glyph
 * atlas (see gui/client/tools/genfont.c). The OS itself ships no TrueType
 * rasterizer: each font_<name>.c holds, per size, an 8-bit coverage blob plus a
 * per-glyph metrics table, and glyphs are alpha-blended onto a surface at draw
 * time. To add a font, run `make fonts` over a new .ttf and register the
 * generated gfx_font_t with gfx_set_font().
 *
 * Five sizes are baked per font; pick one with gfx_set_size(). Sizes are a
 * semantic scale (tiny..huge), not point values, so swapping fonts keeps call
 * sites stable. */
#ifndef VIBEOS_GFX_FONT_H
#define VIBEOS_GFX_FONT_H

#include <stdint.h>

typedef enum {
    GFX_FONT_TINY = 0,
    GFX_FONT_SMALL,
    GFX_FONT_NORMAL,
    GFX_FONT_LARGE,
    GFX_FONT_HUGE,
    GFX_FONT_NSIZES
} gfx_font_size_t;

/* One glyph's atlas entry. (x,y) offsets are relative to the pen position on
 * the baseline; the coverage bitmap is `w*h` bytes at `alpha + off`. */
typedef struct gfx_glyph {
    uint8_t  w, h;        /* coverage bitmap dimensions (pixels) */
    int8_t   xoff, yoff;  /* top-left of bitmap relative to pen/baseline */
    uint8_t  advance;     /* pen advance to the next glyph */
    uint32_t off;         /* byte offset of this glyph in the alpha blob */
} gfx_glyph_t;

/* One font rendered at one size. Glyphs cover ASCII [first,last]; codepoints
 * outside the range have no bitmap. line_h/ascent drive vertical layout, and
 * cell_w (the max advance) is the cell width for forced-monospace use. */
typedef struct gfx_face {
    int16_t            ascent, descent;   /* px; descent <= 0 (below baseline) */
    int16_t            line_h, cell_w;    /* px line pitch / monospace cell */
    uint8_t            first, last;       /* ASCII range, inclusive */
    const gfx_glyph_t *glyphs;            /* [last-first+1] */
    const uint8_t     *alpha;             /* coverage blob */
} gfx_face_t;

typedef struct gfx_font {
    const char *name;
    gfx_face_t  faces[GFX_FONT_NSIZES];
} gfx_font_t;

/* Fonts generated by genfont. */
extern const gfx_font_t gfx_font_chicago;   /* proportional UI font */
extern const gfx_font_t gfx_font_mono;      /* serif monospace (terminal) */

#endif
