/* genfont — bake a TrueType file into a libgfx glyph atlas (build-time, host).
 *
 *   genfont <font.ttf> <c_identifier> <out.c>
 *
 * Rasterizes printable ASCII at the five semantic sizes (tiny..huge) using
 * stb_truetype and emits a self-contained C file defining
 * `const gfx_font_t gfx_font_<c_identifier>` — an 8-bit coverage blob plus
 * per-size glyph metric tables. The target links only the generated .c; it
 * never sees stb_truetype or the .ttf. Run via `make fonts`.
 *
 * This is host code: it uses libc + malloc + libm and is compiled with the
 * system gcc, not the musl cross-toolchain.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

/* Pixel heights for GFX_FONT_TINY..HUGE. Keep in sync with gfx_font_size_t. */
static const int SIZES[] = { 9, 11, 13, 18, 24 };
static const char *SIZE_NAMES[] = { "TINY", "SMALL", "NORMAL", "LARGE", "HUGE" };
#define NSIZES ((int)(sizeof SIZES / sizeof SIZES[0]))

#define FIRST 0x20   /* space */
#define LAST  0x7E   /* tilde */
#define NGLYPH (LAST - FIRST + 1)

/* One baked glyph, mirrors gfx_glyph_t for emission. */
typedef struct {
    int w, h, xoff, yoff, adv;
    unsigned off;             /* offset into the shared coverage blob */
} glyph_t;

static int iround(float v) { return (int)(v < 0 ? v - 0.5f : v + 0.5f); }

static unsigned char *read_file(const char *path, long *len) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "genfont: cannot open %s\n", path); exit(1); }
    fseek(f, 0, SEEK_END); *len = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *buf = malloc(*len);
    if (fread(buf, 1, *len, f) != (size_t)*len) { fprintf(stderr, "genfont: short read\n"); exit(1); }
    fclose(f);
    return buf;
}

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <font.ttf> <c_identifier> <out.c>\n", argv[0]);
        return 1;
    }
    const char *ttf_path = argv[1], *name = argv[2], *out_path = argv[3];

    long ttf_len;
    unsigned char *ttf = read_file(ttf_path, &ttf_len);
    stbtt_fontinfo info;
    if (!stbtt_InitFont(&info, ttf, stbtt_GetFontOffsetForIndex(ttf, 0))) {
        fprintf(stderr, "genfont: stbtt_InitFont failed\n"); return 1;
    }

    /* Coverage blob, grown as glyphs are rasterized; one blob for the whole
       font, glyph offsets are absolute into it. */
    unsigned char *blob = NULL; size_t blob_len = 0, blob_cap = 0;
    glyph_t glyphs[NSIZES][NGLYPH];
    int face_asc[NSIZES], face_desc[NSIZES], face_lineh[NSIZES], face_cell[NSIZES];

    int v_asc, v_desc, v_gap;
    stbtt_GetFontVMetrics(&info, &v_asc, &v_desc, &v_gap);

    for (int si = 0; si < NSIZES; si++) {
        float scale = stbtt_ScaleForPixelHeight(&info, (float)SIZES[si]);
        face_asc[si]   = iround(v_asc  * scale);
        face_desc[si]  = iround(v_desc * scale);
        face_lineh[si] = iround((v_asc - v_desc + v_gap) * scale);
        int cell = 0;

        for (int c = FIRST; c <= LAST; c++) {
            glyph_t *g = &glyphs[si][c - FIRST];
            int aw, lsb;
            stbtt_GetCodepointHMetrics(&info, c, &aw, &lsb);
            g->adv = iround(aw * scale);

            int w = 0, h = 0, xo = 0, yo = 0;
            unsigned char *bmp = stbtt_GetCodepointBitmap(&info, scale, scale, c, &w, &h, &xo, &yo);
            g->w = w; g->h = h; g->xoff = xo; g->yoff = yo;
            g->off = (unsigned)blob_len;

            if (w < 0 || w > 255 || h < 0 || h > 255 ||
                xo < -128 || xo > 127 || yo < -128 || yo > 127 ||
                g->adv < 0 || g->adv > 255) {
                fprintf(stderr, "genfont: glyph 0x%02x at %dpx out of metric range\n", c, SIZES[si]);
                return 1;
            }
            size_t n = (size_t)w * h;
            if (n) {
                if (blob_len + n > blob_cap) {
                    blob_cap = (blob_len + n) * 2;
                    blob = realloc(blob, blob_cap);
                }
                memcpy(blob + blob_len, bmp, n);
                blob_len += n;
            }
            if (bmp) stbtt_FreeBitmap(bmp, NULL);

            int reach = g->xoff + g->w;        /* rightmost inked column */
            if (g->adv > cell) cell = g->adv;
            if (reach > cell) cell = reach;
        }
        face_cell[si] = cell;
        fprintf(stderr, "  %-6s %2dpx  asc=%d desc=%d line=%d cell=%d\n",
                SIZE_NAMES[si], SIZES[si], face_asc[si], face_desc[si],
                face_lineh[si], face_cell[si]);
    }

    /* ---- emit ---- */
    FILE *o = fopen(out_path, "w");
    if (!o) { fprintf(stderr, "genfont: cannot write %s\n", out_path); return 1; }

    fprintf(o, "/* Generated by gui/client/tools/genfont from %s — do not edit.\n", ttf_path);
    fprintf(o, " * Regenerate with `make fonts`. */\n");
    fprintf(o, "#include \"gfx_font.h\"\n\n");

    fprintf(o, "static const uint8_t %s_alpha[] = {", name);
    for (size_t i = 0; i < blob_len; i++) {
        if (i % 20 == 0) fprintf(o, "\n    ");
        fprintf(o, "%u,", blob[i]);
    }
    fprintf(o, "\n};\n\n");

    for (int si = 0; si < NSIZES; si++) {
        fprintf(o, "static const gfx_glyph_t %s_g%d[] = {\n", name, si);
        for (int gi = 0; gi < NGLYPH; gi++) {
            glyph_t *g = &glyphs[si][gi];
            fprintf(o, "    {%d,%d,%d,%d,%d,%u},  /* 0x%02x %s */\n",
                    g->w, g->h, g->xoff, g->yoff, g->adv, g->off,
                    FIRST + gi,
                    (FIRST + gi == '\\') ? "backslash" :
                    (FIRST + gi == '*') ? "star" : "");
        }
        fprintf(o, "};\n\n");
    }

    fprintf(o, "const gfx_font_t gfx_font_%s = {\n", name);
    fprintf(o, "    \"%s\",\n", name);
    fprintf(o, "    {\n");
    for (int si = 0; si < NSIZES; si++) {
        fprintf(o, "        { %d, %d, %d, %d, %d, %d, %s_g%d, %s_alpha }, /* %s */\n",
                face_asc[si], face_desc[si], face_lineh[si], face_cell[si],
                FIRST, LAST, name, si, name, SIZE_NAMES[si]);
    }
    fprintf(o, "    },\n};\n");
    fclose(o);

    fprintf(stderr, "genfont: wrote %s (%zu glyph bytes, %d sizes)\n",
            out_path, blob_len, NSIZES);
    return 0;
}
